// Consent versioning helper (gap I9)
// Tracks exactly which ToS/privacy-policy/disclaimer version a user accepted and when.
// Needed for PDPL compliance and for defending the "not legal advice" disclaimer.

import { db } from "@/lib/db";
import { audit } from "@/lib/audit";

// Current versions of all consent documents
// Bump these when the document text changes materially
export const CURRENT_CONSENT_VERSIONS = {
  terms_of_service: "1.0.0",
  privacy_policy: "1.0.0",
  not_legal_advice: "1.0.0",
  data_processing: "1.0.0",
} as const;

export type ConsentType = keyof typeof CURRENT_CONSENT_VERSIONS;

// Hash the document text so we can prove exactly what was accepted
async function hashText(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hashBuffer))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// The actual text of each consent document (kept in code for now; in production
// these would be versioned documents in the DB with their own review workflow)
export const CONSENT_TEXTS: Record<ConsentType, { ar: string; en: string }> = {
  terms_of_service: {
    ar: "أوافق على شروط استخدام منصة حقي. هذه المنصة أداة مساعدة ذاتية وليست بديلًا عن التمثيل القانوني. كل مستند يغادر المنصة إما معلومات فقط أو مرّ بمراجعة محامٍ.",
    en: "I agree to the Haqqi platform terms of use. This platform is a self-help tool, not a substitute for legal representation. Every document that leaves the platform is either informational only or has passed through the Lawyer Review workflow.",
  },
  privacy_policy: {
    ar: "أوافق على سياسة الخصوصية. تُعالج بياناتي الشخصية وفق قانون حماية البيانات الشخصية الأردني. يُقلَّل من إرسال المعلومات الشخصية إلى مزودي الذكاء الاصطناعي الخارجيين قدر الإمكان.",
    en: "I agree to the privacy policy. My personal data is processed per Jordan's Personal Data Protection Law. PII sent to external AI providers is minimized.",
  },
  not_legal_advice: {
    ar: "أقرّ بأن المعلومات والمسودات المُولّدة بواسطة حقي ليست فتوى قانونية. الأرقام التقديرية تعتمد على قواعد قانونية معتمدة لكنها ليست ضمانًا بنتيجة.",
    en: "I acknowledge that information and drafts generated by Haqqi are not legal advice. Estimated figures are based on lawyer-approved rules but are not guaranteed outcomes.",
  },
  data_processing: {
    ar: "أوافق على معالجة بيانات قضيتي (تفاصيل الحادث، الإصابات، المستندات) لأغراض تقديم خدمات المنصة، بما في ذلك الصياغة بالذكاء الاصطناعي والبحث في RAG.",
    en: "I consent to processing my case data (accident details, injuries, documents) for the purpose of providing platform services, including AI drafting and RAG search.",
  },
};

export async function recordConsent(opts: {
  userId?: string;
  consentType: ConsentType;
  ipAddress?: string;
  userAgent?: string;
}): Promise<{ id: string; version: string; documentHash: string }> {
  const version = CURRENT_CONSENT_VERSIONS[opts.consentType];
  const text = CONSENT_TEXTS[opts.consentType].ar; // hash the Arabic text as canonical
  const documentHash = await hashText(text);

  const record = await db.consentRecord.create({
    data: {
      userId: opts.userId ?? null,
      consentType: opts.consentType,
      version,
      documentHash,
      ipAddress: opts.ipAddress ?? null,
      userAgent: opts.userAgent ?? null,
    },
  });

  await audit.consentAccepted(opts.userId, opts.consentType, version);

  return {
    id: record.id,
    version,
    documentHash,
  };
}

export async function getUserConsents(userId: string) {
  return db.consentRecord.findMany({
    where: { userId, withdrawnAt: null },
    orderBy: { acceptedAt: "desc" },
  });
}

export async function hasUserAcceptedLatestConsent(userId: string, consentType: ConsentType): Promise<boolean> {
  const latest = await db.consentRecord.findFirst({
    where: { userId, consentType, withdrawnAt: null },
    orderBy: { acceptedAt: "desc" },
  });
  return latest?.version === CURRENT_CONSENT_VERSIONS[consentType];
}
