"use client";

import { useEffect, useState } from "react";
import { useAppStore } from "@/lib/i18n/store";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { FileText, Shield, Scale, Database, Loader2, CheckCircle2, ChevronLeft, ChevronRight } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

const CONSENTS = [
  {
    type: "terms_of_service" as const,
    icon: FileText,
    labelAr: "شروط الاستخدام",
    labelEn: "Terms of Service",
    summaryAr: "أداة مساعدة ذاتية، ليست بديلًا عن محامٍ",
    summaryEn: "Self-help tool, not a substitute for a lawyer",
    bodyAr:
      "هذه المنصة أداة مساعدة ذاتية وليست بديلًا عن التمثيل القانوني. كل مستند يغادر المنصة إما معلومات فقط أو مرّ بمراجعة محامٍ (القسم ٧). استخدامك للمنصة يعني قبولك لهذه الشروط.",
    bodyEn:
      "This platform is a self-help tool, not a substitute for legal representation. Every document that leaves the platform is either informational only or has passed through the Lawyer Review workflow (Section 7). Using the platform means you accept these terms.",
  },
  {
    type: "privacy_policy" as const,
    icon: Shield,
    labelAr: "سياسة الخصوصية",
    labelEn: "Privacy Policy",
    summaryAr: "بياناتك تُعالج وفق قانون حماية البيانات الأردني",
    summaryEn: "Your data is processed per Jordan's PDPL",
    bodyAr:
      "تُعالج بياناتك الشخصية وفق قانون حماية البيانات الشخصية الأردني. يُقلَّل من إرسال المعلومات الشخصية إلى مزودي الذكاء الاصطناعي الخارجيين قدر الإمكان عبر إخفاء الهويات والهواتف والبريد الإلكتروني تلقائيًا. يمكنك طلب تصدير بياناتك أو حذفها في أي وقت من صفحة الخصوصية.",
    bodyEn:
      "Your personal data is processed per Jordan's Personal Data Protection Law (PDPL). PII sent to external AI providers is minimized through automatic redaction of IDs, phones, and emails. You can request data export or deletion at any time from the Privacy page.",
  },
  {
    type: "not_legal_advice" as const,
    icon: Scale,
    labelAr: "إقرار ليس فتوى قانونية",
    labelEn: "Not Legal Advice",
    summaryAr: "المسودات وال تقديرات ليست فتوى قانونية",
    summaryEn: "Drafts and estimates are not legal advice",
    bodyAr:
      "أقرّ بأن المعلومات والمسودات المُولّدة بواسطة حقي ليست فتوى قانونية. الأرقام التقديرية تعتمد على قواعد قانونية معتمدة من محامٍ لكنها ليست ضمانًا بنتيجة. كل أرقام المواد القانونية عناصر نائبة بانتظار تأكيد المستشار القانوني (القسم ٧.٤).",
    bodyEn:
      "I acknowledge that information and drafts generated by Haqqi are not legal advice. Estimated figures are based on lawyer-approved rules but are not guaranteed outcomes. All legal article numbers are placeholders pending legal counsel confirmation (Section 7.4).",
  },
  {
    type: "data_processing" as const,
    icon: Database,
    labelAr: "موافقة معالجة البيانات",
    labelEn: "Data Processing",
    summaryAr: "معالجة بيانات قضيتي لتقديم الخدمات",
    summaryEn: "Processing my case data to provide services",
    bodyAr:
      "أوافق على معالجة بيانات قضيتي (تفاصيل الحادث، الإصابات، المستندات) لأغراض تقديم خدمات المنصة، بما في ذلك الصياغة بالذكاء الاصطناعي والبحث في RAG. تُحفظ البيانات بشكل آمن ويمكنني سحب هذه الموافقة في أي وقت.",
    bodyEn:
      "I consent to processing my case data (accident details, injuries, documents) for the purpose of providing platform services, including AI drafting and RAG search. Data is stored securely and I can withdraw this consent at any time.",
  },
];

export const CONSENTS_KEY = "haqqi-consents-accepted-v1";

interface ConsentGateProps {
  onAccepted?: () => void;
}

export function ConsentGate({ onAccepted }: ConsentGateProps = {}) {
  const lang = useAppStore((s) => s.lang);
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [accepted, setAccepted] = useState<Record<string, boolean>>({});
  const [submitting, setSubmitting] = useState(false);
  const [accordionValue, setAccordionValue] = useState<string>("");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const stored = localStorage.getItem(CONSENTS_KEY);
    if (!stored) {
      const timer = setTimeout(() => setOpen(true), 800);
      return () => clearTimeout(timer);
    }
  }, []);

  async function handleAcceptAll() {
    setSubmitting(true);
    try {
      for (const c of CONSENTS) {
        await fetch("/api/consents", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ consentType: c.type }),
        });
      }
      localStorage.setItem(CONSENTS_KEY, new Date().toISOString());
      setOpen(false);
      onAccepted?.();
      toast({
        title: lang === "ar" ? "تم قبول الموافقات" : "Consents accepted",
        description: lang === "ar" ? "يمكنك الآن استخدام المنصة بالكامل." : "You can now fully use the platform.",
      });
    } finally {
      setSubmitting(false);
    }
  }

  function toggleConsent(type: string) {
    setAccepted((prev) => ({ ...prev, [type]: !prev[type] }));
  }

  const checkedCount = CONSENTS.filter((c) => accepted[c.type]).length;
  const allChecked = checkedCount === CONSENTS.length;
  const Arrow = lang === "ar" ? ChevronLeft : ChevronRight;

  return (
    <Dialog
      open={open}
      onOpenChange={(v) => {
        if (!submitting && !v) {
          setOpen(false);
        }
      }}
    >
      <DialogContent className="max-w-md p-0 gap-0 overflow-hidden">
        {/* Compact header with brand gradient */}
        <div className="haqqi-gradient px-5 py-4 text-white">
          <DialogTitle className="text-base font-bold flex items-center gap-2 text-white">
            <Shield className="h-5 w-5" />
            {lang === "ar" ? "موافقات مطلوبة" : "Required Consents"}
          </DialogTitle>
          <DialogDescription className="text-xs text-white/80 mt-1">
            {lang === "ar"
              ? `${checkedCount} من ${CONSENTS.length} مُحدّد — راجع كل بند بالضغط عليه`
              : `${checkedCount} of ${CONSENTS.length} selected — tap any item to review`}
          </DialogDescription>
        </div>

        {/* Accordion — compact, one line per consent when collapsed */}
        <div className="px-3 py-2 max-h-[50vh] overflow-y-auto haqqi-scroll">
          <Accordion
            type="single"
            collapsible
            value={accordionValue}
            onValueChange={setAccordionValue}
            className="w-full"
          >
            {CONSENTS.map((c) => {
              const Icon = c.icon;
              const isChecked = !!accepted[c.type];
              return (
                <AccordionItem key={c.type} value={c.type} className="border-b last:border-0">
                  <div className="flex items-center gap-2 px-1 py-1">
                    <button
                      onClick={() => toggleConsent(c.type)}
                      className="flex items-center gap-2 flex-1 min-w-0 text-start"
                      aria-label={`Toggle ${c.labelEn}`}
                    >
                      <div
                        className={cn(
                          "flex h-5 w-5 items-center justify-center rounded border-2 transition-all shrink-0",
                          isChecked
                            ? "bg-brand border-brand text-white"
                            : "border-muted-foreground/30 hover:border-brand/50",
                        )}
                      >
                        {isChecked && <CheckCircle2 className="h-3.5 w-3.5" />}
                      </div>
                      <Icon className={cn("h-4 w-4 shrink-0", isChecked ? "text-brand" : "text-muted-foreground")} />
                      <div className="flex-1 min-w-0">
                        <div className={cn("text-sm font-medium truncate", isChecked && "text-brand")}>
                          {lang === "ar" ? c.labelAr : c.labelEn}
                        </div>
                        <div className="text-[10px] text-muted-foreground truncate">
                          {lang === "ar" ? c.summaryAr : c.summaryEn}
                        </div>
                      </div>
                    </button>
                    <AccordionTrigger className="h-8 w-8 p-0 hover:no-underline shrink-0" />
                  </div>
                  <AccordionContent className="pb-3 pt-1 px-1 text-xs text-muted-foreground leading-relaxed">
                    {lang === "ar" ? c.bodyAr : c.bodyEn}
                  </AccordionContent>
                </AccordionItem>
              );
            })}
          </Accordion>
        </div>

        {/* Sticky footer with accept button */}
        <div className="border-t px-4 py-3 bg-muted/30 space-y-2">
          <Button
            onClick={handleAcceptAll}
            disabled={!allChecked || submitting}
            className="bg-brand text-white hover:bg-brand/90 w-full h-10 gap-2"
          >
            {submitting ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : allChecked ? (
              <CheckCircle2 className="h-4 w-4" />
            ) : null}
            {lang === "ar" ? "أوافق على الكل ومتابعة" : "Agree to all and continue"}
            {allChecked && <Arrow className="h-4 w-4" />}
          </Button>
          {!allChecked && (
            <p className="text-[10px] text-muted-foreground text-center">
              {lang === "ar"
                ? `حدّد ${CONSENTS.length - checkedCount} المتبقية للمتابعة`
                : `Select ${CONSENTS.length - checkedCount} more to continue`}
            </p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
