// RTL Arabic PDF generation (PRD §5.1.3, §9.2)
// Uses jsPDF with DejaVu Sans embedded (165 Arabic glyphs) for proper Arabic rendering.
// Note: DejaVu Sans does not include an Arabic shaping engine, so letters render in
// isolated form (not joined). For fully-shaped Arabic text, a production build should
// embed Noto Sans Arabic and use a shaping library (e.g., arabic-reshaper + python-bidi
// via a Python sidecar, or @react-pdf/renderer with React rendering).
//
// This implementation provides:
// - Proper RTL layout (text aligned right, lines reversed)
// - Arabic glyph rendering (letters visible, just not joined)
// - Brand header, metadata block, disclaimer, page numbers
// - Multi-page support

import { jsPDF } from "jspdf";
import { readFileSync } from "fs";
import { join } from "path";

let fontLoaded = false;
let fontBase64: string | null = null;
let fontBoldBase64: string | null = null;

function loadFonts() {
  if (fontLoaded) return;
  try {
    const fontPath = join(process.cwd(), "public", "fonts", "DejaVuSans.ttf");
    const fontBoldPath = join(process.cwd(), "public", "fonts", "DejaVuSans-Bold.ttf");
    fontBase64 = readFileSync(fontPath).toString("base64");
    fontBoldBase64 = readFileSync(fontBoldPath).toString("base64");
  } catch (e) {
    console.warn("[pdf] Could not load DejaVu fonts, falling back to helvetica:", e);
  }
  fontLoaded = true;
}

// Reverse RTL text line by line (preserving Latin words within Arabic lines)
function shapeRtl(text: string): string {
  return text.split("\n").map((line) => {
    // Detect if line is mostly Arabic
    const arabicChars = (line.match(/[\u0600-\u06FF]/g) ?? []).length;
    const latinChars = (line.match(/[a-zA-Z]/g) ?? []).length;
    if (arabicChars > latinChars) {
      // Reverse the line character-by-character for RTL display
      // (proper shaping would join letters, but jsPDF without a shaping engine
      // renders them isolated — this is a known limitation documented in PRD §9.2)
      return line.split("").reverse().join("");
    }
    return line;
  }).join("\n");
}

export function generateDraftPDF(opts: {
  title: string;
  content: string;
  language: "ar" | "en";
  caseId?: string;
  draftId?: string;
  metadata?: Record<string, string>;
}): Buffer {
  const { title, content, language, caseId, draftId, metadata = {} } = opts;

  loadFonts();

  const doc = new jsPDF({ unit: "pt", format: "a4" });

  // Register the Arabic-capable font
  if (fontBase64) {
    doc.addFileToVFS("DejaVuSans.ttf", fontBase64);
    doc.addFont("DejaVuSans.ttf", "DejaVuSans", "normal");
    if (fontBoldBase64) {
      doc.addFileToVFS("DejaVuSans-Bold.ttf", fontBoldBase64);
      doc.addFont("DejaVuSans-Bold.ttf", "DejaVuSans", "bold");
    }
    doc.setFont("DejaVuSans");
  }

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const maxWidth = pageWidth - 2 * margin;
  const isRtl = language === "ar";

  // Header bar
  doc.setFillColor(20, 80, 90); // brand teal
  doc.rect(0, 0, pageWidth, 60, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("DejaVuSans", "bold");
  doc.text("Haqqi - حقي", margin, 38);
  doc.setFontSize(10);
  doc.setFont("DejaVuSans", "normal");
  doc.text("Your Rights After a Car Accident in Jordan", pageWidth - margin, 38, { align: "right" });

  // Title
  doc.setTextColor(20, 40, 50);
  doc.setFontSize(16);
  doc.setFont("DejaVuSans", "bold");
  const titleY = 90;
  const shapedTitle = isRtl ? shapeRtl(title) : title;
  doc.text(shapedTitle, isRtl ? pageWidth - margin : margin, titleY);

  // Metadata block
  doc.setFontSize(9);
  doc.setFont("DejaVuSans", "normal");
  doc.setTextColor(100, 100, 100);
  let metaY = titleY + 20;
  const metaEntries: Array<[string, string]> = [
    ["Generated", new Date().toLocaleString(language === "ar" ? "ar-u-nu-latn" : "en-JO")],
    ...(caseId ? [["Case ID", caseId] as [string, string]] : []),
    ...(draftId ? [["Draft ID", draftId] as [string, string]] : []),
    ...Object.entries(metadata),
  ];
  for (const [k, v] of metaEntries) {
    const line = `${k}: ${v}`;
    doc.text(isRtl ? shapeRtl(line) : line, isRtl ? pageWidth - margin : margin, metaY);
    metaY += 14;
  }

  // Disclaimer
  doc.setTextColor(180, 80, 40);
  doc.setFontSize(8);
  const disclaimer = language === "ar"
    ? "تنبيه: هذه الوثيقة مولّدة بواسطة حقي. الأرقام القانونية عناصر نائبة بانتظار اعتماد المستشار القانوني."
    : "Disclaimer: This document was generated by Haqqi. Legal numbers are placeholders pending counsel approval.";
  doc.text(isRtl ? shapeRtl(disclaimer) : disclaimer, isRtl ? pageWidth - margin : margin, metaY + 10, {
    maxWidth,
    align: isRtl ? "right" : "left",
  });

  // Content
  doc.setTextColor(20, 40, 50);
  doc.setFontSize(11);
  doc.setFont("DejaVuSans", "normal");

  const contentY = metaY + 35;
  const shapedContent = isRtl ? shapeRtl(content) : content;
  const lines = doc.splitTextToSize(shapedContent, maxWidth);

  let y = contentY;
  const lineHeight = 16;
  for (const line of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, isRtl ? pageWidth - margin : margin, y, {
      align: isRtl ? "right" : "left",
    });
    y += lineHeight;
  }

  // Footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const footerText = language === "ar"
      ? `صفحة ${i} من ${pageCount} — حقي`
      : `Page ${i} of ${pageCount} — Haqqi`;
    doc.text(
      isRtl ? shapeRtl(footerText) : footerText,
      pageWidth / 2,
      pageHeight - 20,
      { align: "center" },
    );
  }

  return Buffer.from(doc.output("arraybuffer"));
}
