// RTL Arabic PDF generation (PRD §5.1.3, §9.2)
// Uses jsPDF. For proper Arabic shaping, a production build should embed Noto Sans Arabic
// and use a shaping engine (e.g., arabic-reshaper + python-bidi via a Python sidecar).
// For the MVP demo we generate a PDF that lays out the content RTL with Latin fallback.

import { jsPDF } from "jspdf";

function shapeArabic(text: string): string {
  // Reverse for RTL display when no shaping engine is available
  return text.split("\n").map((line) => {
    const tokens = line.split(/(\s+)/);
    return tokens.reverse().join("");
  }).join("\n");
}

export function generateDraftPDF(opts: {
  title: string;
  content: string;
  language: "ar" | "en";
  caseId?: string;
  draftId?: string;
  metadata?: Record<string, string>;
}): Buffer {
  const { title, content, language, caseId, draftId, metadata = {} } = opts;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const maxWidth = pageWidth - 2 * margin;

  // Header bar
  doc.setFillColor(20, 80, 90); // brand teal
  doc.rect(0, 0, pageWidth, 60, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Haqqi - Hqqy", margin, 38);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Your Rights After a Car Accident in Jordan", pageWidth - margin, 38, { align: "right" });

  // Title
  doc.setTextColor(20, 40, 50);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  const titleY = 90;
  doc.text(title, margin, titleY);

  // Metadata block
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  let metaY = titleY + 20;
  const metaEntries: Array<[string, string]> = [
    ["Generated", new Date().toLocaleString(language === "ar" ? "ar-JO" : "en-JO")],
    ...(caseId ? [["Case ID", caseId] as [string, string]] : []),
    ...(draftId ? [["Draft ID", draftId] as [string, string]] : []),
    ...Object.entries(metadata),
  ];
  for (const [k, v] of metaEntries) {
    doc.text(`${k}: ${v}`, margin, metaY);
    metaY += 14;
  }

  // Disclaimer
  doc.setTextColor(180, 80, 40);
  doc.setFontSize(8);
  doc.text(
    language === "ar"
      ? "Tanbeeh: Generated by Haqqi. Legal numbers are placeholders pending counsel approval."
      : "Disclaimer: This document was generated by Haqqi. Legal numbers are placeholders pending counsel approval.",
    margin,
    metaY + 10,
  );

  // Content
  doc.setTextColor(20, 40, 50);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const contentY = metaY + 35;
  const processedContent = language === "ar" ? shapeArabic(content) : content;
  const lines = doc.splitTextToSize(processedContent, maxWidth);

  let y = contentY;
  const lineHeight = 16;
  for (const line of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, language === "ar" ? pageWidth - margin : margin, y, {
      align: language === "ar" ? "right" : "left",
    });
    y += lineHeight;
  }

  // Footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `${language === "ar" ? "Safha" : "Page"} ${i} / ${pageCount}`,
      pageWidth / 2,
      pageHeight - 20,
      { align: "center" },
    );
  }

  return Buffer.from(doc.output("arraybuffer"));
}
